-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 10:27:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema musique
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema musique
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musique` DEFAULT CHARACTER SET utf8 ;
USE `musique` ;

-- -----------------------------------------------------
-- Table `musique`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musique`.`album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `genre` VARCHAR(255) NULL,
  `picture` VARCHAR(255) NULL,
  `artist` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musique`.`track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musique`.`track` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NULL,
  `youtube_url` VARCHAR(255) NULL,
  `id_album` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_track_album_idx` (`id_album` ASC) VISIBLE,
  CONSTRAINT `fk_track_album`
    FOREIGN KEY (`id_album`)
    REFERENCES `musique`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
